name: App Update Notifier

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Manual trigger option

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py

      - name: Configure Git
        run: |
          git config user.name "mbggan"
          git config user.email "mbggan@gmail.com"

      - name: Commit and push changes to app_versions.json
        run: |
          git add app_versions.json
          git commit -m "Update app_versions.json with new app versions" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main

