name: Monitor App Versions

on:
  schedule:
    - cron: "*/5 * * * *"  # This runs every 5 minutes
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  update_app_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Git user
        run: |
          git config --global user.email "${{ secrets.GITHUB_EMAIL }}"
          git config --global user.name "${{ secrets.GITHUB_USERNAME }}"

      - name: Run script to check for updates
        run: |
          python main.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Commit and push changes to app_versions.json
        run: |
          git add app_versions.json
          git commit -m "Update app_versions.json with new app versions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
